sourceSets {
  main.java.srcDirs = [ "src/main/java" ]
  main.resources.srcDirs = [ "src/main/resources" ]
}

dependencies {
  implementation project(":core")
}

jar {
  duplicatesStrategy(DuplicatesStrategy.EXCLUDE)

  from { configurations.compileClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
  manifest {
    attributes 'Main-Class': application.mainClass
  }
}
