plugins {
    id 'application'
}

sourceSets.main.java.srcDirs = [ "src/main/java" ]

dependencies {
    implementation project(":core")
    implementation project(":client")
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

application {
    mainClass = 'ludo.lwjgl3.Lwjgl3Launcher'
}

run {
    workingDir = rootProject.file('assets')
    ignoreExitValue = true

    if (org.gradle.internal.os.OperatingSystem.current() == org.gradle.internal.os.OperatingSystem.MAC_OS) {
        jvmArgs += "-XstartOnFirstThread"
    }
}

jar {
    archiveBaseName = 'ludo'
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    from(rootProject.files('assets')) {
      into 'assets'
    }
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
